### ISSUE TITLE
Document the kind of saturation it produces.

### ISSUE THREAD

**Issue by amano-kenji** [brummer10/GxSaturator.lv2#2]
Does it produce symmetric saturation or asymmetric saturation?

I'm specifically looking to simulate asymmetric saturation to feel a bit of tube warmth.

**Comment by brummer10** [comment]
Wenn I remember correctly it will provide symmetric saturation. 
If you are looking for some tube saturation you may checkout this one:
https://github.com/brummer10/ModularAmpToolKit.lv2

It's a plugin set of pre/power amp tube simulators reduced to bare bones and a set of Impulse responses to cover different amp types.

**Comment by amano-kenji** [comment]
Never mind. I found airwindows-lv2 tube2 plugin. It produces tube saturation while using minimal CPU resource.
